<?php 
/* Template Name: Rev */

// if (isset($_GET['post_id'])) {
get_header();

?>
<?php echo '<p>[vc_row type="full_width_content" full_screen_row_position="middle" bg_color="#f2f2f2" scene_position="center" text_color="dark" text_align="left" top_padding="7%" bottom_padding="7%" overlay_strength="0.3" shape_divider_position="bottom"][vc_column column_padding="no-extra-padding" column_padding_position="all" background_color_opacity="1" background_hover_color_opacity="1" column_link_target="_self" column_shadow="none" column_border_radius="none" width="1/1" tablet_width_inherit="default" tablet_text_alignment="default" phone_text_alignment="default" column_border_width="none" column_border_style="solid"][testimonial_slider style="multiple_visible_minimal" star_rating_color="extra-color-gradient-1"][testimonial star_rating="100%" title="Testimonial" id="1485906261983-10fe9b-6176" name="Aura Brooks" subtitle="Graphic Designer, Owl Eyes" quote="By far the best team Ive ever worked with. They truly understood the look I was going for and completely nailed it! I would highly recommend them as a company, you simply just wont find any better team!" tab_id="1599761952853-5"] Click the edit button to add your testimonial. [/testimonial][testimonial star_rating="80%" title="Testimonial" id="1485906261988-8fe9b-6176" name="Eve Crawford" subtitle="Product Designer, That Biz" quote="It was really fun getting to know the team during the project. They were all helpful in answering my questions and made me feel completely at ease. The design ended up being twice as good as I could have ever envisioned!" tab_id="1599761952865-7"] Click the edit button to add your testimonial. [/testimonial][testimonial star_rating="91%" title="Testimonial" id="1485906262005-7fe9b-6176" name="Jack Graham" subtitle="Co founder, Coffee Inc" quote="Im wondering why I never contacted these guys sooner! Seriously, they all have commendable talent in their respective fields and knocked my concept out of the ballpark. Thanks for an amazing experience!" tab_id="1599761952875-1"] Click the edit button to add your testimonial. [/testimonial][testimonial star_rating="91%" title="Testimonial" id="1485906262024-5fe9b-6176" name="Zak Reid" subtitle="Instructor, Skate Nao" quote="Salient is by far the most astonishing WP theme out there! I literally could not be happier that I chose to buy your theme! Your regular updates and superb attention to detail blows me away every time I visit my new site!" tab_id="1599761952884-0"] Click the edit button to add your testimonial. [/testimonial][testimonial star_rating="100%" title="Testimonial" id="1485906262039-2fe9b-6176" name="Jake Smith" subtitle="Instructor, Skate Nao" quote="Salient is by far the most astonishing WP theme out there! I literally could not be happier that I chose to buy your theme! Your regular updates and superb attention to detail blows me away every time I visit my new site!" tab_id="1599761952915-2"] Click the edit button to add your testimonial. [/testimonial][/testimonial_slider][/vc_column][/vc_row]</p>'; ?>

<?php echo do_shortcode( ' [vc_row][vc_column][testimonial_slider style="multiple_visible_minimal" star_rating_color="extra-color-gradient-1"][testimonial star_rating="100%" title="Testimonial" id="1485906261983-10fe9b-6176" name="Aura Brooks" subtitle="Graphic Designer, Owl Eyes" quote="By far the best team Ive ever worked with. They truly understood the look I was going for and completely nailed it! I would highly recommend them as a company, you simply just wont find any better team!" tab_id="1599761952853-5"] Click the edit button to add your testimonial. [/testimonial][testimonial star_rating="80%" title="Testimonial" id="1485906261988-8fe9b-6176" name="Eve Crawford" subtitle="Product Designer, That Biz" quote="It was really fun getting to know the team during the project. They were all helpful in answering my questions and made me feel completely at ease. The design ended up being twice as good as I could have ever envisioned!" tab_id="1599761952865-7"] Click the edit button to add your testimonial. [/testimonial][testimonial star_rating="91%" title="Testimonial" id="1485906262005-7fe9b-6176" name="Jack Graham" subtitle="Co founder, Coffee Inc" quote="Im wondering why I never contacted these guys sooner! Seriously, they all have commendable talent in their respective fields and knocked my concept out of the ballpark. Thanks for an amazing experience!" tab_id="1599761952875-1"] Click the edit button to add your testimonial. [/testimonial][testimonial star_rating="91%" title="Testimonial" id="1485906262024-5fe9b-6176" name="Zak Reid" subtitle="Instructor, Skate Nao" quote="Salient is by far the most astonishing WP theme out there! I literally could not be happier that I chose to buy your theme! Your regular updates and superb attention to detail blows me away every time I visit my new site!" tab_id="1599761952884-0"] Click the edit button to add your testimonial. [/testimonial][testimonial star_rating="100%" title="Testimonial" id="1485906262039-2fe9b-6176" name="Jake Smith" subtitle="Instructor, Skate Nao" quote="Salient is by far the most astonishing WP theme out there! I literally could not be happier that I chose to buy your theme! Your regular updates and superb attention to detail blows me away every time I visit my new site!" tab_id="1599761952915-2"] Click the edit button to add your testimonial. [/testimonial][/testimonial_slider][/vc_column][/vc_row] ' );?>

<?php echo do_shortcode( ' 
[vc_column_text]
<h3><a href="home">home</a></h3>
[/vc_column_text]
' );?>
<?php
// $post_id= $_GET['post_id'];
// var_dump($post_id);
get_footer();
// }
// else{
// 	wp_redirect(home_url().'/application-profile');
// }
?>